# @package _group_
_target_: src.models.foundation.moirai.Moirai
repo_id: "Salesforce/moirai-2.0-R-small"
filename: "model.ckpt"
context_length: 4096
patch_size: 32
num_samples: 100
target_dim: 1
feat_dynamic_real_dim: 0
past_feat_dynamic_real_dim: 0
batch_size: 32
alias: "Moirai"
